//! Bounded solve-json v1 request generation and success invariants.

use arbitrary::{Result, Unstructured};
use ballistics_engine::solve_json::{
    AtmosphereV1, DragModelV1, DropsReferenceV1, EffectsV1, PressureReferenceV1, ProjectileV1,
    ResolvedWindV1, RifleV1, SamplingV1,
    SchemaVersionV1, ShotV1, SolveRequestV1, SolveSuccessV1, SolverMethodV1, SolverV1,
    TwistDirectionV1, WindReferenceV1, WindSegmentV1, WindShearModelV1, WindV1,
    MAX_SOLVE_JSON_SAMPLES_V1,
};

use crate::domain::{ranged, wild};

/// Upper bound for any valid downrange work generated by this harness.
pub const MAX_FUZZ_RANGE_M: f64 = 250.0;

/// Upper bound for a generated segmented-wind vector.
pub const MAX_FUZZ_WIND_SEGMENTS: usize = 8;

fn drag_model(u: &mut Unstructured<'_>) -> Result<DragModelV1> {
    Ok(match u.int_in_range(0u8..=8)? {
        0 => DragModelV1::G1,
        1 => DragModelV1::G2,
        2 => DragModelV1::G5,
        3 => DragModelV1::G6,
        4 => DragModelV1::G7,
        5 => DragModelV1::G8,
        6 => DragModelV1::GI,
        7 => DragModelV1::GS,
        _ => DragModelV1::RA4,
    })
}

fn solver_method(u: &mut Unstructured<'_>) -> Result<SolverMethodV1> {
    Ok(match u.int_in_range(0u8..=2)? {
        0 => SolverMethodV1::Euler,
        1 => SolverMethodV1::Rk4,
        _ => SolverMethodV1::Rk45,
    })
}

fn twist_direction(u: &mut Unstructured<'_>) -> Result<TwistDirectionV1> {
    Ok(if u.arbitrary()? {
        TwistDirectionV1::Right
    } else {
        TwistDirectionV1::Left
    })
}

fn maybe_bool(u: &mut Unstructured<'_>) -> Result<Option<bool>> {
    if u.arbitrary()? {
        Ok(Some(u.arbitrary()?))
    } else {
        Ok(None)
    }
}

/// Generate an optional wind-reference mode (MBA-1368). `Compass` without a
/// `shot_azimuth_rad` is a solver error the harness tolerates, so it is fuzzed freely.
fn maybe_wind_reference(u: &mut Unstructured<'_>) -> Result<Option<WindReferenceV1>> {
    Ok(if u.arbitrary()? {
        Some(if u.arbitrary()? {
            WindReferenceV1::Compass
        } else {
            WindReferenceV1::Shooter
        })
    } else {
        None
    })
}

/// Generate an optional drops-reference mode (MBA-1403).
fn maybe_drops_reference(u: &mut Unstructured<'_>) -> Result<Option<DropsReferenceV1>> {
    Ok(if u.arbitrary()? {
        Some(if u.arbitrary()? {
            DropsReferenceV1::Target
        } else {
            DropsReferenceV1::Los
        })
    } else {
        None
    })
}

fn maybe_ranged(u: &mut Unstructured<'_>, lo: f64, hi: f64) -> Result<Option<f64>> {
    if u.arbitrary()? {
        Ok(Some(ranged(u, lo, hi)?))
    } else {
        Ok(None)
    }
}

fn maybe_wild(u: &mut Unstructured<'_>) -> Result<Option<f64>> {
    if u.arbitrary()? {
        Ok(Some(wild(u)?))
    } else {
        Ok(None)
    }
}

/// Produce either a bounded valid value or a value which must be rejected before doing work.
fn bounded_or_invalid(u: &mut Unstructured<'_>, lo: f64, hi: f64) -> Result<f64> {
    Ok(match u.int_in_range(0u8..=7)? {
        0 => f64::NAN,
        1 => f64::INFINITY,
        2 => f64::NEG_INFINITY,
        3 => 0.0,
        4 => -ranged(u, lo.abs().max(f64::EPSILON), hi.abs().max(1.0))?,
        _ => ranged(u, lo, hi)?,
    })
}

fn maybe_bounded_or_invalid(u: &mut Unstructured<'_>, lo: f64, hi: f64) -> Result<Option<f64>> {
    if u.arbitrary()? {
        Ok(Some(bounded_or_invalid(u, lo, hi)?))
    } else {
        Ok(None)
    }
}

/// A single, always solve-able request: every field is finite and inside the bounds
/// `decode_solve_request_v1`'s range checks accept, so the service is expected to solve it
/// successfully (barring a rare semantic conflict such as `Compass` wind without
/// `shot_azimuth_rad`, see `maybe_wind_reference`).
///
/// `pub` so fuzz targets whose property only makes sense downstream of a successful solve
/// (e.g. `roundtrip_resolved`) can reuse this generator directly instead of building their own
/// -- see the memory note on this crate about hand-built DTO literals breaking CI on any
/// schema change.
pub fn valid_request(u: &mut Unstructured<'_>) -> Result<SolveRequestV1> {
    let max_range_m = ranged(u, 20.0, MAX_FUZZ_RANGE_M)?;
    let zero_distance_m = if u.int_in_range(0u8..=7)? == 0 {
        Some(ranged(u, 20.0, max_range_m.clamp(20.0, 100.0))?)
    } else {
        None
    };
    let muzzle_angle_rad = if zero_distance_m.is_some() {
        None
    } else {
        maybe_ranged(u, -0.03, 0.10)?
    };
    let method = solver_method(u)?;

    let wind = match u.int_in_range(0u8..=2)? {
        0 => WindV1::default(),
        1 => WindV1 {
            speed_mps: Some(ranged(u, 0.0, 30.0)?),
            direction_from_rad: Some(ranged(u, -std::f64::consts::TAU, std::f64::consts::TAU)?),
            vertical_speed_mps: maybe_ranged(u, -10.0, 10.0)?,
            segments: None,
            wind_reference: maybe_wind_reference(u)?,
        },
        _ => {
            let count = usize::from(u.int_in_range(1u8..=4)?);
            let mut segments = Vec::with_capacity(count);
            for index in 0..count {
                let until_distance_m = max_range_m * (index + 1) as f64 / count as f64;
                segments.push(WindSegmentV1 {
                    until_distance_m,
                    speed_mps: ranged(u, 0.0, 30.0)?,
                    direction_from_rad: ranged(u, -std::f64::consts::TAU, std::f64::consts::TAU)?,
                    vertical_speed_mps: maybe_ranged(u, -10.0, 10.0)?,
                });
            }
            WindV1 {
                speed_mps: None,
                direction_from_rad: None,
                vertical_speed_mps: None,
                segments: Some(segments),
                wind_reference: maybe_wind_reference(u)?,
            }
        }
    };

    let effect = u.int_in_range(0u8..=3)?;
    let coriolis = effect == 1;
    let magnus = effect == 2;
    let enhanced_spin_drift = effect == 3;

    // 0.36.0: generate the wind-shear model rather than pinning it, so the boundary-layer
    // path is fuzzed instead of only its disabled default. Segmented wind combined with a
    // shear model is a documented `conflicting_fields` refusal (the solver's segment lookup
    // takes precedence over its shear branch), and this generator's contract is that every
    // request it produces solves, so the model stays absent whenever segments were generated.
    let wind_shear_model = if wind.segments.is_some() {
        None
    } else {
        match u.int_in_range(0u8..=4)? {
            0 => None,
            1 => Some(WindShearModelV1::None),
            2 => Some(WindShearModelV1::Logarithmic),
            3 => Some(WindShearModelV1::PowerLaw),
            _ => Some(WindShearModelV1::EkmanSpiral),
        }
    };

    Ok(SolveRequestV1 {
        schema_version: SchemaVersionV1,
        projectile: ProjectileV1 {
            mass_kg: ranged(u, 0.002, 0.030)?,
            diameter_m: ranged(u, 0.004, 0.012)?,
            length_m: maybe_ranged(u, 0.010, 0.060)?,
            drag_model: drag_model(u)?,
            ballistic_coefficient: ranged(u, 0.1, 1.2)?,
        },
        rifle: RifleV1 {
            muzzle_velocity_mps: ranged(u, 300.0, 1_200.0)?,
            sight_height_m: maybe_ranged(u, 0.0, 0.15)?,
            muzzle_height_m: maybe_ranged(u, 0.0, 2.0)?,
            twist_rate_m_per_turn: maybe_ranged(u, 0.1, 0.5)?,
            twist_direction: if u.arbitrary()? {
                Some(twist_direction(u)?)
            } else {
                None
            },
            sight_offset_lateral_m: maybe_ranged(u, -0.1, 0.1)?,
        },
        shot: ShotV1 {
            max_range_m,
            zero_distance_m,
            muzzle_angle_rad,
            aim_azimuth_rad: maybe_ranged(u, -0.05, 0.05)?,
            shot_azimuth_rad: maybe_ranged(u, -std::f64::consts::PI, std::f64::consts::PI)?,
            shooting_angle_rad: maybe_ranged(u, -0.5, 0.5)?,
            cant_angle_rad: maybe_ranged(u, -std::f64::consts::PI, std::f64::consts::PI)?,
            target_height_m: maybe_ranged(u, -5.0, 5.0)?,
            ground_threshold_m: Some(-100.0),
            zero_poi_up_m: maybe_ranged(u, -0.05, 0.05)?,
            zero_poi_right_m: maybe_ranged(u, -0.05, 0.05)?,
            drops_reference: maybe_drops_reference(u)?,
        },
        atmosphere: AtmosphereV1 {
            altitude_m: maybe_ranged(u, -500.0, 5_000.0)?,
            temperature_k: maybe_ranged(u, 220.0, 330.0)?,
            pressure_pa: maybe_ranged(u, 50_000.0, 110_000.0)?,
            relative_humidity: maybe_ranged(u, 0.0, 1.0)?,
            latitude_rad: if coriolis || u.arbitrary()? {
                Some(ranged(
                    u,
                    -std::f64::consts::FRAC_PI_2,
                    std::f64::consts::FRAC_PI_2,
                )?)
            } else {
                None
            },
            // MBA-1397: generate the pressure reference rather than pinning it, so the
            // QNH reduction path is actually fuzzed instead of only its absolute default.
            pressure_reference: if u.arbitrary()? {
                Some(if u.arbitrary()? {
                    PressureReferenceV1::Qnh
                } else {
                    PressureReferenceV1::Absolute
                })
            } else {
                None
            },
        },
        wind,
        solver: SolverV1 {
            method: Some(method),
            // A valid fixed-step request never asks for more than 1000 integration steps per
            // second of flight. RK45 ignores this value but retaining the same bound is simpler.
            time_step_s: Some(ranged(u, 0.001, 0.02)?),
        },
        effects: EffectsV1 {
            magnus: Some(magnus),
            coriolis: Some(coriolis),
            enhanced_spin_drift: Some(enhanced_spin_drift),
            wind_shear_model,
        },
        sampling: SamplingV1 {
            interval_m: Some(ranged(u, 0.05, 25.0)?),
        },
        // A dedicated reticle-description generator is a separate harness; the reticle
        // module carries its own unit + overflow-regression tests. Fuzzed as absent here.
        reticle: None,
        // BC5D corrections point at filesystem tables; fuzzing filesystem paths belongs
        // to a dedicated harness, and the differential target's 0.21.5 reference engine
        // has no corrections concept. Fuzzed as absent.
        corrections: None,
    })
}

fn hostile_wind(u: &mut Unstructured<'_>) -> Result<WindV1> {
    Ok(match u.int_in_range(0u8..=4)? {
        0 => WindV1::default(),
        1 => WindV1 {
            speed_mps: maybe_bounded_or_invalid(u, 0.0, 100.0)?,
            direction_from_rad: maybe_wild(u)?,
            vertical_speed_mps: maybe_wild(u)?,
            segments: None,
            wind_reference: maybe_wind_reference(u)?,
        },
        2 => WindV1 {
            // Exercise partial constant-wind and scalar/segment conflicts.
            speed_mps: maybe_bounded_or_invalid(u, 0.0, 100.0)?,
            direction_from_rad: maybe_wild(u)?,
            vertical_speed_mps: maybe_wild(u)?,
            segments: Some(Vec::new()),
            wind_reference: maybe_wind_reference(u)?,
        },
        _ => {
            let count =
                usize::from(u.int_in_range(1u8..=u8::try_from(MAX_FUZZ_WIND_SEGMENTS).unwrap())?);
            let mut segments = Vec::with_capacity(count);
            for _ in 0..count {
                segments.push(WindSegmentV1 {
                    until_distance_m: bounded_or_invalid(u, 1.0, MAX_FUZZ_RANGE_M)?,
                    speed_mps: bounded_or_invalid(u, 0.0, 100.0)?,
                    direction_from_rad: wild(u)?,
                    vertical_speed_mps: maybe_wild(u)?,
                });
            }
            WindV1 {
                speed_mps: if u.arbitrary()? { maybe_wild(u)? } else { None },
                direction_from_rad: None,
                vertical_speed_mps: None,
                segments: Some(segments),
                wind_reference: maybe_wind_reference(u)?,
            }
        }
    })
}

/// Build a request which is always resource-bounded but may be semantically hostile.
///
/// Most requests start valid and receive one to six mutations. This gets the fuzzer deeper than
/// making every field independently invalid, while still covering programmatic NaN and infinity
/// values which cannot cross the JSON wire.
pub fn bounded_hostile_request(u: &mut Unstructured<'_>) -> Result<SolveRequestV1> {
    let mut request = valid_request(u)?;
    if u.int_in_range(0u8..=3)? == 0 {
        return Ok(request);
    }

    let mutations = usize::from(u.int_in_range(1u8..=6)?);
    for _ in 0..mutations {
        match u.int_in_range(0u8..=27)? {
            0 => request.projectile.mass_kg = wild(u)?,
            1 => request.projectile.diameter_m = wild(u)?,
            2 => request.projectile.length_m = maybe_wild(u)?,
            3 => request.projectile.ballistic_coefficient = wild(u)?,
            4 => request.rifle.muzzle_velocity_mps = bounded_or_invalid(u, 250.0, 1_500.0)?,
            5 => request.rifle.sight_height_m = maybe_bounded_or_invalid(u, 0.0, 10.0)?,
            6 => request.rifle.muzzle_height_m = maybe_wild(u)?,
            7 => request.rifle.twist_rate_m_per_turn = maybe_wild(u)?,
            8 => request.shot.max_range_m = bounded_or_invalid(u, 1.0, MAX_FUZZ_RANGE_M)?,
            9 => {
                request.shot.zero_distance_m =
                    maybe_bounded_or_invalid(u, 1.0, MAX_FUZZ_RANGE_M.min(100.0))?
            }
            10 => request.shot.muzzle_angle_rad = maybe_bounded_or_invalid(u, -0.1, 0.3)?,
            11 => request.shot.aim_azimuth_rad = maybe_wild(u)?,
            12 => request.shot.shot_azimuth_rad = maybe_wild(u)?,
            13 => request.shot.shooting_angle_rad = maybe_bounded_or_invalid(u, -0.7, 0.7)?,
            14 => request.shot.cant_angle_rad = maybe_wild(u)?,
            15 => request.shot.target_height_m = maybe_wild(u)?,
            16 => request.shot.ground_threshold_m = maybe_wild(u)?,
            17 => request.atmosphere.altitude_m = maybe_wild(u)?,
            18 => request.atmosphere.temperature_k = maybe_wild(u)?,
            19 => request.atmosphere.pressure_pa = maybe_wild(u)?,
            20 => request.atmosphere.relative_humidity = maybe_wild(u)?,
            21 => request.atmosphere.latitude_rad = maybe_wild(u)?,
            22 => request.wind = hostile_wind(u)?,
            23 => request.solver.method = Some(solver_method(u)?),
            24 => request.solver.time_step_s = maybe_bounded_or_invalid(u, 0.001, 0.02)?,
            25 => {
                request.effects.magnus = maybe_bool(u)?;
                request.effects.coriolis = maybe_bool(u)?;
                request.effects.enhanced_spin_drift = maybe_bool(u)?;
            }
            26 => {
                // A tiny but finite interval exercises the checked response-resource path. It
                // cannot enlarge integration work and the service must reject >10,000 samples.
                request.sampling.interval_m = maybe_bounded_or_invalid(u, 0.001, 25.0)?
            }
            _ => {
                // Explicitly exercise the structural zero/muzzle-angle conflict.
                request.shot.zero_distance_m = Some(ranged(u, 1.0, 100.0)?);
                request.shot.muzzle_angle_rad = Some(ranged(u, -0.1, 0.3)?);
            }
        }
    }
    Ok(request)
}

fn assert_finite(path: &str, value: f64) {
    assert!(
        value.is_finite(),
        "successful {path} is non-finite: {value}"
    );
}

fn assert_optional_finite(path: &str, value: Option<f64>) {
    if let Some(value) = value {
        assert_finite(path, value);
    }
}

/// Assert the service's successful-output resource and finiteness contract.
///
/// This deliberately walks the typed DTO. `serde_json` serializes non-finite floats as JSON null,
/// so serialization by itself is not proof that a successful result contains only finite numbers.
pub fn assert_finite_success(success: &SolveSuccessV1) {
    let request = &success.resolved_request;
    assert_finite(
        "resolved_request.projectile.mass_kg",
        request.projectile.mass_kg,
    );
    assert_finite(
        "resolved_request.projectile.diameter_m",
        request.projectile.diameter_m,
    );
    assert_optional_finite(
        "resolved_request.projectile.length_m",
        request.projectile.length_m,
    );
    assert_finite(
        "resolved_request.projectile.ballistic_coefficient",
        request.projectile.ballistic_coefficient,
    );
    assert_finite(
        "resolved_request.rifle.muzzle_velocity_mps",
        request.rifle.muzzle_velocity_mps,
    );
    assert_finite(
        "resolved_request.rifle.sight_height_m",
        request.rifle.sight_height_m,
    );
    assert_finite(
        "resolved_request.rifle.muzzle_height_m",
        request.rifle.muzzle_height_m,
    );
    assert_finite(
        "resolved_request.rifle.twist_rate_m_per_turn",
        request.rifle.twist_rate_m_per_turn,
    );
    assert_finite(
        "resolved_request.shot.max_range_m",
        request.shot.max_range_m,
    );
    assert_optional_finite(
        "resolved_request.shot.zero_distance_m",
        request.shot.zero_distance_m,
    );
    for (path, value) in [
        ("muzzle_angle_rad", request.shot.muzzle_angle_rad),
        ("aim_azimuth_rad", request.shot.aim_azimuth_rad),
        ("shot_azimuth_rad", request.shot.shot_azimuth_rad),
        ("shooting_angle_rad", request.shot.shooting_angle_rad),
        ("cant_angle_rad", request.shot.cant_angle_rad),
        ("target_height_m", request.shot.target_height_m),
        ("ground_threshold_m", request.shot.ground_threshold_m),
    ] {
        assert_finite(&format!("resolved_request.shot.{path}"), value);
    }
    for (path, value) in [
        ("altitude_m", request.atmosphere.altitude_m),
        ("temperature_k", request.atmosphere.temperature_k),
        ("pressure_pa", request.atmosphere.pressure_pa),
        ("relative_humidity", request.atmosphere.relative_humidity),
    ] {
        assert_finite(&format!("resolved_request.atmosphere.{path}"), value);
    }
    assert_optional_finite(
        "resolved_request.atmosphere.latitude_rad",
        request.atmosphere.latitude_rad,
    );
    match &request.wind {
        ResolvedWindV1::Constant(wind) => {
            assert_finite("resolved_request.wind.speed_mps", wind.speed_mps);
            assert_finite(
                "resolved_request.wind.direction_from_rad",
                wind.direction_from_rad,
            );
            assert_finite(
                "resolved_request.wind.vertical_speed_mps",
                wind.vertical_speed_mps,
            );
        }
        ResolvedWindV1::Segmented(wind) => {
            assert!(
                wind.segments.len() <= MAX_FUZZ_WIND_SEGMENTS,
                "successful segmented wind escaped the generator bound"
            );
            for (index, segment) in wind.segments.iter().enumerate() {
                for (path, value) in [
                    ("until_distance_m", segment.until_distance_m),
                    ("speed_mps", segment.speed_mps),
                    ("direction_from_rad", segment.direction_from_rad),
                    ("vertical_speed_mps", segment.vertical_speed_mps),
                ] {
                    assert_finite(
                        &format!("resolved_request.wind.segments[{index}].{path}"),
                        value,
                    );
                }
            }
        }
    }
    assert_finite(
        "resolved_request.solver.time_step_s",
        request.solver.time_step_s,
    );
    assert_finite(
        "resolved_request.sampling.interval_m",
        request.sampling.interval_m,
    );

    for (path, value) in [
        ("actual_range_m", success.summary.actual_range_m),
        ("maximum_height_m", success.summary.maximum_height_m),
        ("time_of_flight_s", success.summary.time_of_flight_s),
        ("terminal_speed_mps", success.summary.terminal_speed_mps),
        ("terminal_energy_j", success.summary.terminal_energy_j),
    ] {
        assert_finite(&format!("summary.{path}"), value);
    }
    assert_optional_finite("summary.stability_factor", success.summary.stability_factor);
    assert_optional_finite("summary.spin_drift_m", success.summary.spin_drift_m);

    assert!(
        !success.samples.is_empty(),
        "successful response has no samples"
    );
    assert!(
        success.samples.len() <= MAX_SOLVE_JSON_SAMPLES_V1,
        "successful response exceeded the public sample limit"
    );
    for (index, sample) in success.samples.iter().enumerate() {
        for (path, value) in [
            ("distance_m", sample.distance_m),
            ("time_s", sample.time_s),
            ("speed_mps", sample.speed_mps),
            ("energy_j", sample.energy_j),
            ("drop_m", sample.drop_m),
            ("windage_m", sample.windage_m),
            ("mach", sample.mach),
        ] {
            assert_finite(&format!("samples[{index}].{path}"), value);
        }
    }
    let terminal = success.samples.last().expect("non-empty checked above");
    assert_eq!(
        terminal.distance_m.to_bits(),
        success.summary.actual_range_m.to_bits(),
        "terminal sample and summary range diverged"
    );

    success
        .validate_for_serialization()
        .expect("successful response must remain within serialization limits");
    let encoded = serde_json::to_vec(success).expect("successful response must serialize");
    let _: SolveSuccessV1 =
        serde_json::from_slice(&encoded).expect("serialized success must decode");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_requests_keep_all_work_multipliers_bounded_when_valid() {
        let bytes = vec![0xA5; 16_384];
        let mut u = Unstructured::new(&bytes);
        let request = bounded_hostile_request(&mut u).expect("enough generator input");
        if request.shot.max_range_m.is_finite() && request.shot.max_range_m > 0.0 {
            assert!(request.shot.max_range_m <= MAX_FUZZ_RANGE_M);
        }
        if let Some(distance) = request.shot.zero_distance_m {
            if distance.is_finite() && distance > 0.0 {
                assert!(distance <= 100.0);
            }
        }
        if let Some(step) = request.solver.time_step_s {
            if step.is_finite() && step > 0.0 {
                assert!(step >= 0.001);
            }
        }
        if let Some(segments) = request.wind.segments {
            assert!(segments.len() <= MAX_FUZZ_WIND_SEGMENTS);
        }
    }
}
