// MBA-1316: multi-observation joint MV+BC calibration (`true-velocity --observed`).
//
// The forward-model helper below reproduces the exact assembly the CLI's truing
// forward model uses (`solve_trajectory_drop` in src/main.rs), via the public
// engine API, so synthetic round-trip observations are self-consistent with what
// the fitter solves.

use serde_json::Value;
use std::process::Command;

use ballistics_engine::{
    calculate_zero_angle_with_conditions, AtmosphericConditions, BallisticInputs, DragModel,
    TrajectorySolver, WindConditions,
};

fn get_cli_binary() -> &'static str {
    env!("CARGO_BIN_EXE_ballistics")
}

fn fallback_bullet_length_m(diameter_m: f64, mass_kg: f64) -> f64 {
    let est = ballistics_engine::stability::estimate_bullet_length_m(diameter_m, mass_kg);
    if est > 0.0 {
        est
    } else {
        diameter_m * 4.5
    }
}

/// Imperial-default atmosphere the CLI resolves when temp/pressure/humidity/alt
/// are omitted: 59 F, 29.92 inHg, 50% RH, 0 ft. Mirrors src/main.rs.
struct Load {
    mv_fps: f64,
    bc: f64,
    mass_gr: f64,
    diameter_in: f64,
    zero_yd: f64,
    sight_in: f64,
}

/// Reproduces `solve_trajectory_drop` -> drop in MIL (small-angle) at `range_yd`.
fn forward_drop_mil(load: &Load, range_yd: f64) -> f64 {
    let velocity_ms = load.mv_fps * 0.3048;
    let mass_kg = load.mass_gr * 0.0000647989;
    let diameter_m = load.diameter_in * 0.0254;
    let zero_m = load.zero_yd * 0.9144;
    let range_m = range_yd * 0.9144;
    let sight_height_m = load.sight_in * 0.0254;
    let temperature_c = (59.0 - 32.0) * 5.0 / 9.0;
    let pressure_hpa = 29.92 * 33.8639;

    let mut inputs = BallisticInputs {
        muzzle_velocity: velocity_ms,
        bc_value: load.bc,
        bc_type: DragModel::G1,
        bullet_mass: mass_kg,
        bullet_diameter: diameter_m,
        bullet_length: fallback_bullet_length_m(diameter_m, mass_kg),
        sight_height: sight_height_m,
        target_distance: range_m + 100.0,
        use_bc_segments: false,
        bc_segments_data: None,
        use_rk4: true,
        muzzle_angle: 0.0,
        ..Default::default()
    };

    let atmosphere = AtmosphericConditions {
        temperature: temperature_c,
        pressure: pressure_hpa,
        humidity: 50.0,
        altitude: 0.0,
    };
    let wind = WindConditions::default();

    let zero_angle = calculate_zero_angle_with_conditions(
        inputs.clone(),
        zero_m,
        sight_height_m,
        wind.clone(),
        atmosphere.clone(),
    )
    .expect("zero angle");
    inputs.muzzle_angle = zero_angle;

    let mut solver = TrajectorySolver::new(inputs, wind, atmosphere);
    solver.set_max_range(range_m + 100.0);
    solver.set_time_step(0.0001);
    let result = solver.solve().expect("solve");
    let idx = result
        .points
        .iter()
        .position(|p| p.position.x >= range_m)
        .expect("reach range");
    // Interpolate to land exactly on range_m, matching the CLI's interpolated
    // multi-observation forward model.
    let y = if idx > 0 {
        let p0 = &result.points[idx - 1];
        let p1 = &result.points[idx];
        let denom = p1.position.x - p0.position.x;
        if denom.abs() < f64::EPSILON {
            p1.position.y
        } else {
            let frac = (range_m - p0.position.x) / denom;
            p0.position.y + frac * (p1.position.y - p0.position.y)
        }
    } else {
        result.points[idx].position.y
    };
    let drop_m = sight_height_m - y;
    (drop_m / range_m) * 1000.0
}

fn run_true_velocity(args: &[&str]) -> std::process::Output {
    Command::new(get_cli_binary())
        .args(args)
        .output()
        .expect("run true-velocity")
}

/// Fit a set of ranges (drops generated by `load`), starting BC = `start_bc`,
/// and return the parsed JSON. `noise` (mil) is added element-wise to the drops.
fn fit_ranges_noisy(load: &Load, ranges: &[f64], start_bc: f64, noise: &[f64]) -> Value {
    let drops: Vec<(f64, f64)> = ranges
        .iter()
        .enumerate()
        .map(|(i, &r)| (r, forward_drop_mil(load, r) + noise.get(i).copied().unwrap_or(0.0)))
        .collect();
    let mut args: Vec<String> = vec![
        "true-velocity".into(),
        "--measured-drop".into(),
        format!("{:.6}", drops[0].1),
        "--range".into(),
        format!("{:.1}", drops[0].0),
    ];
    for d in &drops[1..] {
        args.push("--observed".into());
        args.push(format!("{:.1}:{:.6}", d.0, d.1));
    }
    args.extend(
        [
            "--bc",
            &format!("{start_bc}"),
            "--drag-model",
            "g1",
            "--mass",
            &format!("{}", load.mass_gr),
            "--diameter",
            &format!("{}", load.diameter_in),
            "--output",
            "json",
        ]
        .iter()
        .map(|s| s.to_string()),
    );
    let refs: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
    let out = run_true_velocity(&refs);
    assert!(
        out.status.success(),
        "fit failed: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    serde_json::from_slice(&out.stdout).expect("json")
}

fn fit_ranges(load: &Load, ranges: &[f64], start_bc: f64) -> Value {
    fit_ranges_noisy(load, ranges, start_bc, &[])
}

fn test_load() -> Load {
    Load {
        mv_fps: 2700.0,
        bc: 0.475,
        mass_gr: 168.0,
        diameter_in: 0.308,
        zero_yd: 100.0,
        sight_in: 2.0,
    }
}

/// Synthetic round-trip: generate observations at a known MV/BC across
/// supersonic->near-transonic ranges (300/600/900 yd), add realistic (~0.02 mil)
/// measurement noise, deliberately start BC ~5% low, and require the joint fit
/// to recover MV within 0.5% and BC within 2%.
///
/// Tolerance justification: the fitter reproduces noise-free observations to
/// machine precision (the forward model is shared and interpolated). With
/// ~0.02 mil noise on 300/600/900 the empirical recovery is ~0.3% MV / ~1.1% BC
/// (see the module's calibration notes / src/main.rs threshold comments), so the
/// 0.5%/2% gates carry roughly 1.5x margin over the noise-driven error. BC is the
/// weaker parameter (lower drop sensitivity), hence its looser 2% bound.
#[test]
fn synthetic_round_trip_recovers_mv_and_bc() {
    let load = test_load();
    // Deterministic ~0.02 mil noise (no RNG -> no flakiness), chosen so the
    // middle/near observations pull BC and MV in opposing directions.
    let noise = [0.02, -0.025, 0.015];
    let v = fit_ranges_noisy(&load, &[300.0, 600.0, 900.0], 0.45, &noise);

    assert_eq!(v["mode"], "joint_mv_bc", "should attempt the joint fit");
    assert_eq!(v["bc_fitted"], true);

    let mv = v["fitted_muzzle_velocity"].as_f64().unwrap();
    let bc = v["fitted_bc"].as_f64().unwrap();
    let mv_err = (mv - load.mv_fps).abs() / load.mv_fps;
    let bc_err = (bc - load.bc).abs() / load.bc;
    assert!(
        mv_err <= 0.005,
        "MV recovery {mv:.1} fps off by {:.3}% (>0.5%)",
        mv_err * 100.0
    );
    assert!(
        bc_err <= 0.02,
        "BC recovery {bc:.4} off by {:.3}% (>2%)",
        bc_err * 100.0
    );

    // Per-observation residuals and RMS must be present and small.
    let obs = v["observations"].as_array().unwrap();
    assert_eq!(obs.len(), 3);
    for o in obs {
        assert!(o["residual_mil"].is_number());
        assert!(o["predicted_drop_mil"].is_number());
    }
    assert!(v["rms_residual_mil"].as_f64().unwrap() < 0.1);
}

/// A noise-free round trip should recover the parameters essentially exactly,
/// proving the shared/interpolated forward model is self-consistent.
#[test]
fn synthetic_round_trip_noise_free_is_exact() {
    let load = test_load();
    let v = fit_ranges(&load, &[300.0, 600.0, 900.0], 0.45);
    let mv = v["fitted_muzzle_velocity"].as_f64().unwrap();
    let bc = v["fitted_bc"].as_f64().unwrap();
    assert!((mv - load.mv_fps).abs() / load.mv_fps < 5e-4, "mv={mv}");
    assert!((bc - load.bc).abs() / load.bc < 5e-3, "bc={bc}");
}

/// Ill-conditioned observation set (all short, fully supersonic, closely spaced):
/// BC cannot be separated from MV, so the command must fit MV only, hold BC at
/// the input value, and say why.
#[test]
fn ill_conditioned_set_refuses_joint_and_fits_mv_only() {
    let load = test_load();
    let v = fit_ranges(&load, &[200.0, 250.0, 300.0], 0.45);
    assert_eq!(v["mode"], "mv_only", "short cluster must not attempt joint fit");
    assert_eq!(v["bc_fitted"], false);
    // BC is held exactly at the input.
    assert_eq!(v["fitted_bc"].as_f64().unwrap(), 0.45);
    assert_eq!(v["input_bc"].as_f64().unwrap(), 0.45);
    // A plain-language reason is reported.
    let reason = v["bc_hold_reason"].as_str().unwrap_or("");
    assert!(
        reason.contains("constrain BC") || reason.contains("separate MV from BC"),
        "expected a BC-hold explanation, got: {reason:?}"
    );
    // MV is still fit against the data.
    let mv = v["fitted_muzzle_velocity"].as_f64().unwrap();
    assert!((1000.0..=5000.0).contains(&mv), "mv={mv}");
}

/// Zero `--observed` flags must take the classic single-observation path
/// unchanged: legacy JSON schema, none of the multi-observation fields.
#[test]
fn zero_observed_flags_keep_legacy_schema() {
    let out = run_true_velocity(&[
        "true-velocity",
        "--measured-drop",
        "5.1",
        "--range",
        "600",
        "--bc",
        "0.27",
        "--drag-model",
        "g7",
        "--mass",
        "140",
        "--diameter",
        "0.264",
        "--offline",
        "--output",
        "json",
    ]);
    assert!(out.status.success());
    let v: Value = serde_json::from_slice(&out.stdout).unwrap();
    // Legacy keys present.
    assert!(v["effective_velocity"].is_number());
    assert!(v["calculated_drop_mil"].is_number());
    assert!(v["confidence"].is_string());
    // New multi-observation keys must be absent on this path.
    assert!(v.get("mode").is_none(), "legacy path must not emit 'mode'");
    assert!(v.get("observations").is_none());
    assert!(v.get("fitted_bc").is_none());
}

/// The `--drop-unit` default (mil) must not alter the single-observation path.
#[test]
fn drop_unit_default_does_not_touch_single_obs() {
    let base = [
        "true-velocity",
        "--measured-drop",
        "5.1",
        "--range",
        "600",
        "--bc",
        "0.27",
        "--drag-model",
        "g7",
        "--mass",
        "140",
        "--diameter",
        "0.264",
        "--offline",
        "--output",
        "json",
    ];
    let a = run_true_velocity(&base);
    let mut with_unit = base.to_vec();
    with_unit.push("--drop-unit");
    with_unit.push("mil");
    let b = run_true_velocity(&with_unit);
    assert_eq!(
        a.stdout, b.stdout,
        "explicit --drop-unit mil must not change single-observation output"
    );
}

#[test]
fn duplicate_ranges_error_not_panic() {
    // Primary range 300 duplicated by an --observed 300.
    let out = run_true_velocity(&[
        "true-velocity",
        "--measured-drop",
        "1.3",
        "--range",
        "300",
        "--observed",
        "300:1.3",
        "--bc",
        "0.45",
        "--mass",
        "168",
        "--diameter",
        "0.308",
    ]);
    assert!(!out.status.success());
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("duplicate"), "stderr: {err}");
}

#[test]
fn zero_drop_error_not_panic() {
    let out = run_true_velocity(&[
        "true-velocity",
        "--measured-drop",
        "1.3",
        "--range",
        "300",
        "--observed",
        "600:0",
        "--bc",
        "0.45",
        "--mass",
        "168",
        "--diameter",
        "0.308",
    ]);
    assert!(!out.status.success());
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("non-zero"), "stderr: {err}");
}

#[test]
fn malformed_observed_error_not_panic() {
    let out = run_true_velocity(&[
        "true-velocity",
        "--measured-drop",
        "1.3",
        "--range",
        "300",
        "--observed",
        "600", // missing :DROP
        "--bc",
        "0.45",
        "--mass",
        "168",
        "--diameter",
        "0.308",
    ]);
    assert!(!out.status.success());
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("RANGE:DROP"), "stderr: {err}");
}

/// JSON contract for the joint fit: self-describing legend + unit-labelled keys.
#[test]
fn joint_json_has_legend_and_unit_labeled_keys() {
    let load = test_load();
    let v = fit_ranges(&load, &[300.0, 600.0, 900.0], 0.45);
    assert_eq!(v["mode"], "joint_mv_bc");
    assert_eq!(v["legend"]["units"]["range"], "yd");
    assert_eq!(v["legend"]["units"]["drop"], "mil");
    assert_eq!(v["legend"]["units"]["velocity"], "fps");
    assert_eq!(v["velocity_unit"], "fps");
    assert!(v["rms_residual_mil"].is_number());
    let o0 = &v["observations"][0];
    for key in ["range_yd", "observed_drop_mil", "predicted_drop_mil", "residual_mil"] {
        assert!(o0[key].is_number(), "missing key {key}");
    }
}

/// Metric units: ranges parsed as meters, velocity reported in m/s.
#[test]
fn metric_units_range_in_meters() {
    let load = test_load();
    // 275/550/825 m ~= 300/600/900 yd.
    let drops: Vec<(f64, f64)> = [(275.0, 300.0), (550.0, 600.0), (825.0, 900.0)]
        .iter()
        .map(|&(m, yd)| (m, forward_drop_mil(&load, yd)))
        .collect();
    let out = run_true_velocity(&[
        "true-velocity",
        "--measured-drop",
        &format!("{:.6}", drops[0].1),
        "--range",
        "275",
        "--observed",
        &format!("550:{:.6}", drops[1].1),
        "--observed",
        &format!("825:{:.6}", drops[2].1),
        "--bc",
        "0.45",
        "--drag-model",
        "g1",
        "--mass",
        "168",
        "--diameter",
        "0.308",
        "--units",
        "metric",
        "--output",
        "json",
    ]);
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let v: Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(v["velocity_unit"], "m/s");
    assert_eq!(v["legend"]["units"]["range"], "m");
    assert_eq!(v["observations"][0]["range_m"].as_f64().unwrap(), 275.0);
    // Fitted velocity ~ 2700 fps = ~823 m/s.
    let mv_ms = v["fitted_muzzle_velocity"].as_f64().unwrap();
    assert!((mv_ms - 823.0).abs() < 20.0, "mv_ms={mv_ms}");
}

// -----------------------------------------------------------------------------
// MBA-1405 Task 2: the MV-calibration window (90-100% of the downward Mach 1.2
// crossing of the finally fitted load) — table line, no-window note, the
// per-observation out-of-window stderr warning, the cross-reference to
// `plan-truing`, and additive-only JSON purity.
//
// The transonic fixture below is the same 300/600/900 joint fit
// `src/wasm_tests.rs`'s `true_velocity_multi_observation_matches_native_joint_fit`
// pins to a 2514.5 fps fitted MV — reused here (not regenerated via
// `forward_drop_mil`) so the window figures are pinned against an already-stable,
// cross-surface-verified fit rather than a fresh derivation.
// -----------------------------------------------------------------------------

const TRANSONIC_FIXTURE_ARGS: &[&str] = &[
    "true-velocity",
    "--range",
    "300",
    "--measured-drop",
    "1.8",
    "--observed",
    "600:5.1",
    "--observed",
    "900:10.9",
    "--bc",
    "0.475",
    "-m",
    "168",
    "-d",
    "0.308",
    "--zero-distance",
    "100",
    "--chrono-velocity",
    "2700",
];

/// A very high BC / high velocity load whose downward Mach 1.2 crossing sits well
/// beyond the fixed 3000 yd envelope the window re-solve uses — deliberately
/// unrealistic (BC 2.0), chosen purely to exercise the "no window" branch.
const FULLY_SUPERSONIC_FIXTURE_ARGS: &[&str] = &[
    "true-velocity",
    "--range",
    "300",
    "--measured-drop",
    "0.3",
    "--observed",
    "600:0.65",
    "--bc",
    "2.0",
    "-m",
    "750",
    "-d",
    "0.510",
    "--zero-distance",
    "300",
    "--chrono-velocity",
    "3300",
];

#[test]
fn mv_calibration_window_line_appears_for_a_transonic_fixture() {
    let out = run_true_velocity(TRANSONIC_FIXTURE_ARGS);
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.contains("MV-calibration window: 656.7-729.7 yd (90-100% of the Mach 1.2 distance)"),
        "{stdout}"
    );
}

#[test]
fn no_mv_window_note_for_a_fully_supersonic_fixture() {
    let out = run_true_velocity(FULLY_SUPERSONIC_FIXTURE_ARGS);
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.contains(
            "note: no MV window: trajectory is supersonic through 3109.4 yd; MV is identifiable at any range"
        ),
        "{stdout}"
    );
    assert!(!stdout.contains("MV-calibration window:"), "{stdout}");
}

/// Every one of the transonic fixture's three observations (300/600/900 yd) sits
/// outside its pinned 656.7-729.7 yd window, so all three must warn on stderr.
#[test]
fn out_of_window_observations_warn_on_stderr() {
    let out = run_true_velocity(TRANSONIC_FIXTURE_ARGS);
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let stderr = String::from_utf8_lossy(&out.stderr);
    for r in ["300.0", "600.0", "900.0"] {
        assert!(
            stderr.contains(&format!(
                "warning: observation at {r} is outside the MV-calibration window \
                 (656.7-729.7); MV fits from this range are weakly identified"
            )),
            "missing warning for {r}: {stderr}"
        );
    }
}

/// The no-window fixture has no window to be outside of — the warning loop must
/// not fire at all.
#[test]
fn no_out_of_window_warning_when_there_is_no_window() {
    let out = run_true_velocity(FULLY_SUPERSONIC_FIXTURE_ARGS);
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(!stderr.contains("MV-calibration window"), "{stderr}");
}

#[test]
fn plan_truing_cross_reference_line_appears_exactly_once() {
    let out = run_true_velocity(TRANSONIC_FIXTURE_ARGS);
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let stdout = String::from_utf8_lossy(&out.stdout);
    let needle = "for optimal observation ranges run: ballistics plan-truing";
    assert_eq!(
        stdout.matches(needle).count(),
        1,
        "cross-reference line must appear exactly once: {stdout}"
    );
}

#[test]
fn json_gets_additive_window_fields_only_never_note_text() {
    let mut json_args: Vec<&str> = TRANSONIC_FIXTURE_ARGS.to_vec();
    json_args.extend(["--output", "json"]);
    let out = run_true_velocity(&json_args);
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let raw = String::from_utf8_lossy(&out.stdout);
    assert!(
        !raw.to_lowercase().contains("calibration window"),
        "JSON must carry no note text: {raw}"
    );
    let v: Value = serde_json::from_slice(&out.stdout).unwrap();
    let lo = v["mv_window_start_m"].as_f64().expect("mv_window_start_m present and numeric");
    let hi = v["mv_window_end_m"].as_f64().expect("mv_window_end_m present and numeric");
    assert!(lo > 0.0 && hi > lo, "lo={lo} hi={hi}");
    // 656.7-729.7 yd pinned above, in meters (yd * 0.9144).
    assert!((lo - 656.7 * 0.9144).abs() < 0.5, "lo={lo}");
    assert!((hi - 729.7 * 0.9144).abs() < 0.5, "hi={hi}");
}

#[test]
fn json_window_fields_are_null_when_there_is_no_window() {
    let mut json_args: Vec<&str> = FULLY_SUPERSONIC_FIXTURE_ARGS.to_vec();
    json_args.extend(["--output", "json"]);
    let out = run_true_velocity(&json_args);
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let v: Value = serde_json::from_slice(&out.stdout).unwrap();
    assert!(v["mv_window_start_m"].is_null(), "{v}");
    assert!(v["mv_window_end_m"].is_null(), "{v}");
}

#[test]
fn csv_output_carries_no_window_note_text() {
    let mut csv_args: Vec<&str> = TRANSONIC_FIXTURE_ARGS.to_vec();
    csv_args.extend(["--output", "csv"]);
    let out = run_true_velocity(&csv_args);
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(!stdout.to_lowercase().contains("calibration window"), "{stdout}");
    assert!(!stdout.to_lowercase().contains("mv is identifiable"), "{stdout}");
}

// -----------------------------------------------------------------------------
// MBA-1405 Task 2 fix pass: `mach_1_2_distance_m == None` has two opposite
// physical causes and the report text must distinguish them (task-2-review.md
// Important finding). `FULLY_SUPERSONIC_FIXTURE_ARGS` above covers the load
// that is STILL supersonic through the whole 3000 yd window envelope. The
// fixture below is the opposite: a load that launches BELOW Mach 1.2 (muzzle
// Mach ~0.94 at std atm 59 F, speed of sound ~1116 fps -> ~1050 fps muzzle
// velocity) and so never crosses downward through Mach 1.2 at all — the
// `MachTransitionTracker` only records a *downward* crossing, so this case
// also yields `mach_1_2_distance_m == None`, but for the opposite reason.
// -----------------------------------------------------------------------------

/// A subsonic (e.g. suppressed .300 BLK-class) load, self-consistent via the
/// shared `forward_drop_mil` forward model, sighted in and observed at short
/// suppressed-carbine ranges.
fn never_supersonic_load() -> Load {
    Load {
        mv_fps: 1050.0,
        bc: 0.300,
        mass_gr: 220.0,
        diameter_in: 0.308,
        zero_yd: 25.0,
        sight_in: 2.0,
    }
}

/// Assemble `true-velocity` CLI args for `never_supersonic_load()` observed at
/// 50/100 yd, with `extra` appended verbatim (e.g. `["--output", "json"]`).
fn never_supersonic_fixture_args(extra: &[&str]) -> Vec<String> {
    let load = never_supersonic_load();
    let ranges = [100.0, 400.0];
    let drops: Vec<(f64, f64)> =
        ranges.iter().map(|&r| (r, forward_drop_mil(&load, r))).collect();
    let mut args: Vec<String> = vec![
        "true-velocity".into(),
        "--range".into(),
        format!("{:.1}", drops[0].0),
        "--measured-drop".into(),
        format!("{:.6}", drops[0].1),
        "--observed".into(),
        format!("{:.1}:{:.6}", drops[1].0, drops[1].1),
        "--bc".into(),
        format!("{}", load.bc),
        "-m".into(),
        format!("{}", load.mass_gr),
        "-d".into(),
        format!("{}", load.diameter_in),
        "--zero-distance".into(),
        format!("{}", load.zero_yd),
        "--chrono-velocity".into(),
        format!("{}", load.mv_fps),
    ];
    args.extend(extra.iter().map(|s| s.to_string()));
    args
}

/// Live repro of the review's Important finding: a never-supersonic load must
/// print the NEW "never reaches Mach 1.2" note, not the old "supersonic
/// through" text (which is physically false for this load — it was never
/// supersonic at any point).
#[test]
fn no_mv_window_note_for_a_never_supersonic_fixture() {
    let args = never_supersonic_fixture_args(&[]);
    let refs: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
    let out = run_true_velocity(&refs);
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.contains(
            "note: no MV window: trajectory never reaches Mach 1.2; calibrate muzzle \
             velocity with a chronograph, then collect DSF points"
        ),
        "{stdout}"
    );
    assert!(!stdout.contains("MV-calibration window:"), "{stdout}");
    assert!(!stdout.contains("supersonic through"), "{stdout}");
}

/// JSON purity holds for the never-supersonic cause too: still additive-only
/// null fields, no note text of either flavor.
#[test]
fn json_window_fields_are_null_for_a_never_supersonic_fixture() {
    let args = never_supersonic_fixture_args(&["--output", "json"]);
    let refs: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
    let out = run_true_velocity(&refs);
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let raw = String::from_utf8_lossy(&out.stdout);
    assert!(
        !raw.to_lowercase().contains("calibration window") && !raw.to_lowercase().contains("mach 1.2"),
        "JSON must carry no note text: {raw}"
    );
    let v: Value = serde_json::from_slice(&out.stdout).unwrap();
    assert!(v["mv_window_start_m"].is_null(), "{v}");
    assert!(v["mv_window_end_m"].is_null(), "{v}");
}
