//! MBA-1392: `true-wind` — back-solve the effective crosswind from an observed horizontal
//! miss (wind-call truing).
//!
//! What these pin, at the CLI boundary:
//!   (a) the round trip — a miss generated by a KNOWN crosswind solves back to that wind;
//!   (b) both signs — a right miss solves positive, a left miss negative;
//!   (c) spin drift is subtracted, not read as wind, and its twist rate is REQUIRED;
//!   (d) Coriolis needs latitude AND azimuth, or it is a hard error rather than half-on;
//!   (e) native stdout is EXACTLY the shared formatter's bytes, which is what makes the
//!       WASM terminal (which returns those same bytes) formatter-identical;
//!   (f) design R5-DIRECTION: `--miss` is a LINEAR measurement, so no scope tracking CF
//!       flag exists on this command;
//!   (g) the drop-based truing surface is untouched by the forward-model extension.

use ballistics_engine::cli_api::UnitSystem;
use ballistics_engine::truing::{DragModelArg, TruingTwist};
use ballistics_engine::truing_wind::{
    format_wind_truing_report, modeled_miss_right_m, parse_wind_observation, solve_wind_truing,
    WindTruingOutput, WindTruingRequest,
};
use serde_json::Value;
use std::process::Command;

const BIN: &str = env!("CARGO_BIN_EXE_ballistics");

/// The load every case below uses: 168 gr .308 at 2700 fps, G7 0.475, 1:11 right-hand.
const LOAD: &[&str] = &[
    "-v",
    "2700",
    "-b",
    "0.475",
    "-m",
    "168",
    "-d",
    "0.308",
    "--drag-model",
    "g7",
    "--twist-rate",
    "11",
];

fn run(args: &[&str]) -> std::process::Output {
    Command::new(BIN).args(args).output().expect("run binary")
}

fn run_ok(args: &[&str]) -> std::process::Output {
    let output = run(args);
    assert!(
        output.status.success(),
        "command failed: {args:?}\nstderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    output
}

fn wind_json(extra: &[&str]) -> Value {
    let mut args: Vec<&str> = vec!["true-wind"];
    args.extend_from_slice(LOAD);
    args.extend_from_slice(extra);
    args.extend(["-o", "json"]);
    serde_json::from_slice(&run_ok(&args).stdout).expect("json output")
}

/// The same request the CLI assembles for `LOAD`, used to drive the library directly.
fn library_request(miss_tokens: &[&str]) -> WindTruingRequest {
    WindTruingRequest {
        observations: miss_tokens
            .iter()
            .map(|token| parse_wind_observation(token, UnitSystem::Imperial).expect("parse"))
            .collect(),
        muzzle_velocity_fps: 2700.0,
        bc: 0.475,
        drag_model: DragModelArg::G7,
        mass_gr: 168.0,
        diameter_in: 0.308,
        zero_distance_yd: 100.0,
        sight_height_in: 2.0,
        temperature_f: 59.0,
        pressure_inhg: 29.92,
        humidity_pct: 50.0,
        altitude_ft: 0.0,
        twist: TruingTwist {
            rate_in: 11.0,
            right_hand: true,
        },
        earth: None,
        called_crosswind_mph: None,
    }
}

/// (a) Round trip through the CLI: take the misses a known 8 mph crosswind produces at two
/// ranges (from the engine's own forward model), hand them to `true-wind --miss`, and get
/// 8 mph back at both ranges.
#[test]
fn round_trip_recovers_a_known_crosswind_through_the_cli() {
    let model = library_request(&["500:0", "700:0"]);
    let known_mph = 8.0;
    let misses: Vec<String> = [500.0_f64, 700.0]
        .iter()
        .map(|range_yd| {
            let miss_in =
                modeled_miss_right_m(&model, known_mph, range_yd * 0.9144).expect("forward model")
                    / 0.0254;
            format!("{range_yd}:{miss_in}")
        })
        .collect();

    let doc = wind_json(&["--miss", &misses[0], "--miss", &misses[1]]);
    let effective = doc["effective_crosswind"].as_f64().expect("crosswind");
    assert!(
        (effective - known_mph).abs() < 0.05,
        "recovered {effective} mph, expected {known_mph}"
    );
    for observation in doc["observations"].as_array().expect("observations") {
        let solved = observation["solved_crosswind"].as_f64().expect("solved");
        assert!(
            (solved - known_mph).abs() < 0.05,
            "per-observation {solved} mph, expected {known_mph}"
        );
        assert!(observation["converged"].as_bool().expect("converged"));
    }
    assert_eq!(doc["legend"]["units"]["wind_speed"], "mph");
    assert_eq!(doc["legend"]["units"]["miss"], "in");
    // No latitude/azimuth supplied, so Coriolis is named as absorbed rather than silently
    // folded into the answer.
    let unsubtracted = doc["effects_not_subtracted"]
        .as_array()
        .expect("effects_not_subtracted");
    assert!(unsubtracted
        .iter()
        .any(|e| e.as_str().unwrap_or_default().contains("Coriolis")));
}

/// (b) Sign pins at the CLI boundary: a RIGHT miss solves to a POSITIVE (left-hand,
/// right-pushing) wind; a LEFT miss solves NEGATIVE. This is the contract the `true-wind`
/// help block documents.
#[test]
fn right_miss_solves_positive_and_left_miss_solves_negative() {
    let right = wind_json(&["--miss", "600:18.0"]);
    let solved_right = right["effective_crosswind"].as_f64().expect("crosswind");
    assert!(
        solved_right > 0.0,
        "an impact right of aim must solve to a positive wind, got {solved_right}"
    );

    let left = wind_json(&["--miss", "600:-18.0"]);
    let solved_left = left["effective_crosswind"].as_f64().expect("crosswind");
    assert!(
        solved_left < 0.0,
        "an impact left of aim must solve to a negative wind, got {solved_left}"
    );
    // The two are not mirror images: spin drift (right-hand twist) is subtracted from
    // both, so the left-hand case needs MORE wind in magnitude than the right-hand one.
    assert!(
        solved_left.abs() > solved_right.abs(),
        "right-hand spin drift must make the left miss need more wind: {solved_left} vs \
         {solved_right}"
    );
}

/// (c) Spin drift is attributed to spin, not wind: with no wind at all the right-hand
/// twist still drifts right, and feeding exactly that drift back in solves to ~0 mph. The
/// twist rate itself is required — the command refuses to run without it rather than
/// silently reading spin drift as wind.
#[test]
fn spin_drift_is_subtracted_and_twist_rate_is_required() {
    // The no-wind lateral the model reports for a probe observation is the spin drift.
    let probe = wind_json(&["--miss", "800:20.0"]);
    let spin_in = probe["observations"][0]["no_wind_lateral_in"]
        .as_f64()
        .expect("no_wind_lateral_in");
    assert!(
        spin_in > 1.0,
        "a 1:11 right-hand twist must drift measurably right at 800 yd, got {spin_in} in"
    );

    let spin_only = wind_json(&["--miss", &format!("800:{spin_in}")]);
    let solved = spin_only["effective_crosswind"].as_f64().expect("crosswind");
    assert!(
        solved.abs() < 0.05,
        "pure spin drift must solve to ~0 wind, got {solved} mph"
    );

    // Without --twist-rate the command is a clap error, not a spin-blind solve.
    let output = run(&[
        "true-wind",
        "--miss",
        "600:8.0",
        "-v",
        "2700",
        "-b",
        "0.475",
        "-m",
        "168",
        "-d",
        "0.308",
    ]);
    assert!(!output.status.success(), "missing --twist-rate must fail");
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("--twist-rate"), "{stderr}");
}

/// (d) Coriolis is all-or-nothing: supplying both halves subtracts it (and changes the
/// answer); supplying one half is a hard error, never a half-modelled shot.
#[test]
fn coriolis_needs_both_latitude_and_azimuth() {
    let without = wind_json(&["--miss", "1000:30.0"]);
    let with = wind_json(&[
        "--miss",
        "1000:30.0",
        "--latitude",
        "45",
        "--shot-direction",
        "90",
    ]);
    assert!(with["effects_not_subtracted"]
        .as_array()
        .expect("array")
        .is_empty());
    assert!(with["effects_subtracted"]
        .as_array()
        .expect("array")
        .iter()
        .any(|e| e == "Coriolis"));
    let a = without["effective_crosswind"].as_f64().expect("f64");
    let b = with["effective_crosswind"].as_f64().expect("f64");
    assert!(
        (a - b).abs() > 1e-3,
        "modelling Coriolis must change the solved wind: {a} vs {b}"
    );

    for half in [
        vec!["--latitude", "45"],
        vec!["--shot-direction", "90"],
    ] {
        let mut args: Vec<&str> = vec!["true-wind", "--miss", "1000:30.0"];
        args.extend_from_slice(LOAD);
        args.extend_from_slice(&half);
        let output = run(&args);
        assert!(!output.status.success(), "half an earth frame must fail");
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(
            stderr.contains("Coriolis can be modelled"),
            "{stderr}"
        );
    }
}

/// (e) Formatter parity. The native command prints EXACTLY the bytes
/// `format_wind_truing_report` produces — nothing added, nothing reformatted — and the
/// WASM terminal returns those same bytes from the same function, so the two surfaces
/// cannot drift apart. Checked for all three renderings.
#[test]
fn native_stdout_is_exactly_the_shared_formatter_output() {
    let tokens = ["500:14.0", "700:29.5:0.75"];
    let mut request = library_request(&tokens);
    request.called_crosswind_mph = Some(9.0);
    // Note the second observation carries a sigma, so this also covers the
    // inverse-variance-weighted rendering... but sigmas are all-or-none, so give the
    // first one a sigma too.
    request.observations[0].sigma_m = Some(0.75 * 0.0254);
    let report = solve_wind_truing(&request).expect("solve");

    for (flag, kind) in [
        ("table", WindTruingOutput::Table),
        ("json", WindTruingOutput::Json),
        ("csv", WindTruingOutput::Csv),
    ] {
        let mut args: Vec<&str> = vec![
            "true-wind",
            "--miss",
            "500:14.0:0.75",
            "--miss",
            "700:29.5:0.75",
            "--called-wind",
            "9",
        ];
        args.extend_from_slice(LOAD);
        args.extend(["-o", flag]);
        let stdout = String::from_utf8(run_ok(&args).stdout).expect("utf8");
        let shared = format_wind_truing_report(&report, UnitSystem::Imperial, kind);
        assert_eq!(stdout, shared, "native {flag} output must be the shared bytes");
    }
}

/// (f) Design R5-DIRECTION: the tracking correction factor applies to DIALED observations
/// only. `--miss` is a linear tape measurement off the target, so this command exposes no
/// CF flag at all — both spellings are rejected as unknown arguments.
#[test]
fn no_tracking_cf_flag_exists_on_true_wind() {
    for cf_flag in ["--windage-cf", "--elevation-cf"] {
        let mut args: Vec<&str> = vec!["true-wind", "--miss", "600:12.0"];
        args.extend_from_slice(LOAD);
        args.extend([cf_flag, "0.95"]);
        let output = run(&args);
        assert!(
            !output.status.success(),
            "{cf_flag} must not be accepted by true-wind"
        );
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(
            stderr.contains("unexpected argument") || stderr.contains("--windage-cf")
                || stderr.contains("--elevation-cf"),
            "{stderr}"
        );
    }
}

/// Metric parity: ranges in meters, the linear miss still in inches (the `--drop-unit in`
/// precedent), and the solved wind rendered in m/s — the same physical answer.
#[test]
fn metric_reports_the_same_wind_in_metres_per_second() {
    let imperial = wind_json(&["--miss", "600:18.0"]);
    let mut args: Vec<&str> = vec![
        "true-wind",
        "--units",
        "metric",
        "--miss",
        "548.64:18.0", // 600 yd in metres
        "-v",
        "822.96", // 2700 fps in m/s
        "-b",
        "0.475",
        "-m",
        "10.8862",  // 168 gr in grams
        "-d",
        "7.8232", // 0.308 in in mm
        "--drag-model",
        "g7",
        "--twist-rate",
        "279.4", // 1:11" in mm/turn
    ];
    args.extend(["-o", "json"]);
    let metric: Value = serde_json::from_slice(&run_ok(&args).stdout).expect("json");
    assert_eq!(metric["legend"]["units"]["range"], "m");
    assert_eq!(metric["legend"]["units"]["wind_speed"], "m/s");
    assert_eq!(metric["legend"]["units"]["miss"], "in");
    let mph = imperial["effective_crosswind"].as_f64().expect("f64");
    let mps = metric["effective_crosswind"].as_f64().expect("f64");
    assert!(
        (mps - mph * 0.44704).abs() < 0.02,
        "metric {mps} m/s should match imperial {mph} mph"
    );
}

/// A miss no wind can produce is rejected with a diagnostic naming the solvable band and
/// the sign convention, rather than clamped into a plausible-looking answer.
#[test]
fn an_impossible_miss_is_rejected_with_a_diagnostic() {
    let mut args: Vec<&str> = vec!["true-wind", "--miss", "300:400.0"];
    args.extend_from_slice(LOAD);
    let output = run(&args);
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("no crosswind within"), "{stderr}");
    assert!(stderr.contains("check the sign of --miss"), "{stderr}");
}

/// (g) The MBA-1392 forward-model extension threads wind / spin drift / Coriolis through
/// the truing solver assemblies, so the drop-based commands must be pinned as UNMOVED:
/// with no environment supplied every flag stays off and the calm model is what solves.
/// These are the exact values HEAD produced before the extension landed.
#[test]
fn existing_drop_truing_output_is_unchanged_by_the_forward_model_extension() {
    let single: Value = serde_json::from_slice(
        &run_ok(&[
            "true-velocity",
            "--range",
            "300",
            "--measured-drop",
            "1.8",
            "-b",
            "0.475",
            "-m",
            "168",
            "-d",
            "0.308",
            "--offline",
            "-o",
            "json",
        ])
        .stdout,
    )
    .expect("json");
    assert_eq!(
        single["effective_velocity"].as_f64().expect("f64"),
        2355.46875
    );
    assert_eq!(single["iterations"].as_i64().expect("i64"), 8);
    assert_eq!(
        single["calculated_drop_mil"].as_f64().expect("f64"),
        1.790474723938981
    );

    let multi: Value = serde_json::from_slice(
        &run_ok(&[
            "true-velocity",
            "--range",
            "300",
            "--measured-drop",
            "1.8",
            "--observed",
            "600:5.1",
            "--observed",
            "900:12.4",
            "-b",
            "0.475",
            "-m",
            "168",
            "-d",
            "0.308",
            "--offline",
            "-o",
            "json",
        ])
        .stdout,
    )
    .expect("json");
    assert_eq!(
        multi["fitted_muzzle_velocity"].as_f64().expect("f64"),
        2751.8600017612553
    );
    assert_eq!(multi["fitted_bc"].as_f64().expect("f64"), 0.3137211864942836);
    assert_eq!(
        multi["condition_number"].as_f64().expect("f64"),
        164.60013117624405
    );
    assert_eq!(
        multi["mv_window_start_m"].as_f64().expect("f64"),
        485.1346823453194
    );
}
